-- ReputonBot schema snapshot: v0.1.1 (frozen)
-- This file is an artifact for documentation only. Do not auto-apply in production.

-- 1) platform_rules
CREATE TABLE IF NOT EXISTS public.platform_rules (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform             TEXT UNIQUE NOT NULL,
  system_prompt        TEXT NOT NULL,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT now(),
  name                 TEXT,
  rules                JSONB,
  report_url           TEXT,
  instruction_template TEXT,
  tips                 TEXT,
  example_good         TEXT,
  example_bad          TEXT,
  rules_version        TEXT,
  rules_sources        JSONB
);

-- 2) chat_state
CREATE TABLE IF NOT EXISTS public.chat_state (
  chat_id     BIGINT PRIMARY KEY,
  platform    TEXT NOT NULL,
  updated_at  TIMESTAMP DEFAULT now()
);

-- 3) interactions
CREATE TABLE IF NOT EXISTS public.interactions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tg_user_id   TEXT,
  chat_id      BIGINT,
  platform     TEXT,
  input_text   TEXT,
  output_json  JSONB,
  intent       TEXT,
  request_id   TEXT,
  meta_json    JSONB,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS interactions_by_chat_time
  ON public.interactions (chat_id, created_at DESC);
CREATE INDEX IF NOT EXISTS interactions_request_id_idx
  ON public.interactions (request_id);

-- 4) rate_limits
CREATE TABLE IF NOT EXISTS public.rate_limits (
  chat_id     BIGINT NOT NULL,
  utc_day     DATE   NOT NULL DEFAULT (CURRENT_DATE),
  hits        INTEGER DEFAULT 0,
  threshold   INTEGER DEFAULT 100,
  updated_at  TIMESTAMP DEFAULT now(),
  PRIMARY KEY (chat_id, utc_day)
);
CREATE INDEX IF NOT EXISTS rate_limits_updated_at_idx
  ON public.rate_limits (updated_at DESC);

-- 5) request_cache_content (активный контент-кэш)
CREATE TABLE IF NOT EXISTS public.request_cache_content (
  chat_id     BIGINT NOT NULL,
  text_hash   TEXT   NOT NULL,
  platform    TEXT   NOT NULL,
  result_json JSONB  NOT NULL,
  created_at  TIMESTAMP DEFAULT now(),
  expires_at  TIMESTAMP,
  PRIMARY KEY (chat_id, text_hash, platform)
);
CREATE INDEX IF NOT EXISTS request_cache_content_expires_idx
  ON public.request_cache_content (expires_at);

-- 6) request_cache (legacy cache, not used since v0.1.1)
CREATE TABLE IF NOT EXISTS public.request_cache (
  chat_id     BIGINT NOT NULL,
  utc_day     DATE   NOT NULL,
  request_id  TEXT   NOT NULL,
  response    JSONB,
  status      INTEGER,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT now(),
  PRIMARY KEY (chat_id, utc_day, request_id)
);
